changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Models
      labels:
        - new-model
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
