name: Bug Report
description: Report a bug in inference4j
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: inference4j version
      placeholder: "e.g., 0.1.1"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java version
      placeholder: "e.g., Java 21 (Temurin)"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g., macOS 15, Ubuntu 24.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened, and what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the bug.
      render: java
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: Stack trace
      description: Paste the full stack trace if applicable.
      render: text
    validations:
      required: false
