name: Feature Request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for inference4j? We'd love to hear it. Please describe the use case so we can understand the motivation.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to accomplish? What's missing or difficult today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work? Code examples are welcome.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other approaches or workarounds?
    validations:
      required: false
